### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by madnight** [rhysd/node-github-trend#6]
```
TypeError: Cannot read property 'data' of undefined
    at /home/x/trendy/node_modules/github-trend/build/main.js:72:65
    at Array.map (<anonymous>)
    at /home/x/trendy/node_modules/github-trend/build/main.js:40:18
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Thats happens when i try to execute the example code:

```javascript
var Trending = require("github-trend");
var scraper = new Trending.Scraper();
 
// Empty string means 'all languages' 
scraper.scrapeTrendingReposFullInfo("").then(function(repos){
    repos.forEach(function(repo){
        console.log(repo.owner);
        console.log(repo.name);
        console.log(repo.description);
        console.log(repo.language);
        console.log(repo.allStars);
        console.log(repo.todaysStars);
    });
}).catch(function(err){
    console.log(err.message);
});
```
`scrapeTrendingRepos` works fine, so this issue is only related to `scrapeTrendingReposFullInfo`

**Comment by rhysd** [comment]
This was fixed in #8. Please use v0.1.1.
